### ISSUE TITLE
Evaluate performance of Cstruct (BigArray) vs Bytes/String

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage-crypto#110]
At the moment, most FFI calls (and the public interface) uses `Cstruct.t`. It is worth to evaluate using String/Bytes directly, and measure the performance impact thereof.

**Comment by palainp** [comment]
And in #191 . it seems there is an improvement:
- 1085.8 P256 sign/s main branch
- 1795.8 P256 sign/s with #146

**Comment by hannesm** [comment]
Also see https://blog.robur.coop/articles/speeding-ec-string.html -- the takeaway is let's revise the interfaces to avoid Cstruct.t -- maybe take the approach from digestif (provide _string _bytes _bigstring functions for what is worth it).

**Comment by hannesm** [comment]
The evaluation period is closed now. All feedback from tools (benchmarks) as well as community has been very positive.
