### ISSUE TITLE
Question: Exposing the tag in AES-GCM

### ISSUE THREAD

**Issue by orbitz** [mirage/mirage-crypto#144]
I'm encrypting something in Ocaml and decrypting it in PyCryptodome.  In PyCryptodome, the tag is explicitly exposed and passed in for verification and in mirage-crypto it's implicit.  See the PyCryptodome example here:

https://pycryptodome.readthedocs.io/en/latest/src/examples.html#encrypt-data-with-rsa

What's annoying is that I cannot run the PyCryptodome decryption with verification because I don't have the tag.  And when I decrypt it in PyCryptodome I need to explicitly remove the tag by slicing out the last 16 bytes.

Does anyone understand why these interfaces are different?  And should the tag be exposed in this interface to work with other libraries?

**Comment by hannesm** [comment]
Closing as this is being tracked in #74 (and good news, likely by the end of tomorrow there'll be a fresh release with a revised API)

**Comment by hannesm** [comment]
Please let me know if #171 fits your use case well?
