### ISSUE TITLE
mirage-crypto-rng-eio questions

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage-crypto#169]
Dear @talex5 and @bikallem,

would you mind to elaborate on:
- why does mirage-crypto-rng-eio.opam require "dune >= 3.0"? The dune-project file specifies 2.7. I struggle what the reasoning behind this is
- Shouldn't there be a "ocaml" dependency in that opam file (if the answer is yes, would you mind to elaborate which OCaml version would be suitable)?

Thanks a lot,

Hannes

**Comment by hannesm** [comment]
Also, in respect to #165, could we, now that OCaml 5 is released (and also an initial version of mirage-crypto-rng-eio), improve the CI scripts to avoid further maintenance burden? Do you have by chance some time and ideas how to move?

**Comment by hannesm** [comment]
I don't quite understand what the "OCaml-CI" wants to tell me at https://ci.ocamllabs.io/github/mirage/mirage-crypto/commit/eaeff417bb38f615c3f68fd61536352a33566f3f/variant/(analysis) (after > 4500 lines of output -- I'm lost after the first 20).

**Comment by talex5** [comment]
Regarding the CI, it's because the package depends on "base-domains" and so the CI is looking for a multicore-compatible compiler. However, according to ocaml-version:

```
utop # #require "ocaml-version";;

utop # Ocaml_version.(Configure_options.is_multicore Releases.v5_0_0);;
- : bool = false
```

Replacing base-domains with `"ocaml" {>= "5.0.0"}` should fix it.

**Comment by bikallem** [comment]
>why does mirage-crypto-rng-eio.opam require "dune >= 3.0"? The dune-project file specifies 2.7. I struggle what the reasoning behind this is

I believe this is an oversight from me. 

I will make a PR to fix this along with the OCaml version and possibly the CI issue.

**Comment by hannesm** [comment]
Thanks for your replies, I opened #170 and will see how that works out...

**Comment by hannesm** [comment]
since #170 came through CI, I'm fine with the updated state and will close this.
