### ISSUE TITLE
incompatibility with eqaf 0.10

### ISSUE THREAD

**Issue by c-cube** [mirage/mirage-crypto#239]
it seems that mirage-crypto wants eqaf.cstruct, which is not a thing anymore(?) since eqaf 0.10 and the split with eqaf-cstruct. The package probably either needs a dep on eqaf-cstruct, or a upper bound on eqaf < 0.10.

**Comment by hannesm** [comment]
would you mind to show where `eqaf.cstruct` is wanted by mirage-crypto? our latest release, 1.0, does not require any eqaf.cstruct, neither cstruct. all previous versions have an upper bound in the opam-repository https://github.com/ocaml/opam-repository/pull/26099 https://github.com/ocaml/opam-repository/pull/26107

**Comment by c-cube** [comment]
It's in a private CI build, but I think the issue is that we use a specific checkout of opam repo, so it's on `mirage-crypto.0.11.3`. If this is fixed in 1.0 then let me close the issue :)
