### ISSUE TITLE
Use ocaml-base64 instead internal implementation

### ISSUE THREAD

**Issue by dinosaure** [mirage/mirage-crypto#25]
Currently, `mirage-crypto` uses its own implementation of `base64` where the MirageOS organization has an other [`ocaml-base64`](https:/github.com/mirage/ocaml-base64.git) implementation.

For my perspective, we have 3 issues:
- performance
- tests
- distribution of `mirage-crypto`

### Tests

`ocaml-base64` has, at the end, more tests than what `mirage-crypto` provides. It comes with a fuzzer and [a great work](https://github.com/mirage/ocaml-base64/pull/24) was already done about implementation.

### Performances

`ocaml-base64` comes finally from the `nocrypto`'s `base64.ml` module and we already did some benchmark between an imperative implementation (the old version of `ocaml-base64`) and a functional implementation. Results are available in mirage/ocaml-base64#24.

However, some changes was done then and `mirage-crypto` uses `Cstruct.t` where `ocaml-base64` is only able to compute `bytes` and `string`. I extended the initial benchmark of `ocaml-base64` to include the current version of `mirage-crypto` and a `decode`/`encode` with `Cstruct.{of_string,to_string}`.

This is my result in my computer: [benchmark](https://paste.isomorphis.me/Ecr).

As we can see, the most interesting is `Base64 (cstruct)` which still (for large inputs) faster than the `mirage-crypto` implementation. The benchmark is available into mirage/ocaml-base64#41.

### Distribution

Of course, the main question is about the distribution of `mirage-crypto` where we will add a dependency into a external package. For me, anyone who works on `mirage-crypto` has the ability to, at least, improve `ocaml-base64` and submit a pull-request.

I mean, `ocaml-base64` is under the control of the MirageOS team and it does not own by someone external or not totally aware about MirageOS. So, I don't see any blockers to use `ocaml-base64` here instead.

### Conclusion

This issue wants to follow discussion about a possible integration of `ocaml-base64`, I will prepare a pull request then.

**Comment by hannesm** [comment]
thanks for your issue. could you elaborate a bit on the benchmark you conducted? could you write in a sentence about the results (I don't entirely understand the table you pasted, sorry about that). why is "nocrypto" faster by a factor of two (any theory that explains this, since mirage-crypto's code is just copied from there)? what does the number `:5000` mean? is the benchmark about decode and encode, or either of them? is the input generated randomly or uniformly? is the cstruct (bigarray) interface tested for ocaml-base64, or the string one?

and did you compile mirage-crypto (and the other opam packages) in release or development mode?

**Comment by dinosaure** [comment]
About benchmark:
1) we compare at the beginning 3 implementations
    + `ocaml-base64` (as `Base64`)
    + old version of `ocaml-base64` (as `Nocrypto`)- sorry I believed that it's the version of `nocrypto` but it's `ocaml-base64` < 3.0.0
    + `mirage-crypto` (copy/paste of `base64.ml` into the module)
2) number associated to each lines is the length of the input
3) inputs are completely random (from `/usr/urandom`)
4) benchmarks for each implementation do: `decode(encode(input)`
5) `ocaml-base64` does not give to us a `bigarray` interface, the fourth benchmark (`Base64 (cstruct)`) does: `decode(Cstruct.of_string(encode(Cstruct.to_string(input))))`

**Comment by cfcs** [comment]
1) What are `mjWd/Run` and `Prom/Run` why is not listed for the (Mirage_)`Crypto` ?
2) Could you upload a tarball of the code so we can try this out on a few other machines and (I'd like to see what `perf` has to say about the slow parts) ?
3) Is it correctly understood that in this benchmark we have four implementations, two of them work on `string` (`Base64` and `Nocrypto`) while the other two on `Cstruct.t` (`Crypto` and `Base64 (cstruct)`)?
  - That sounds a bit like comparing apples and oranges; additionally the benchmarks would be more useful if they would split up encode/decode; I don't believe that we have a common scenario where we need to do both in rapid succession?
  - (continued) The `Base64 (cstruct)` benchmarks are presently performing four operations while in practice they would be performing three (for each step): `to_string |> decode |> of_string` and `of_string |> encode |> to_string`. That might manifest differently in separate benchmarks.
  - @hannesm correct me if I'm wrong, but I think we could live with a base64 implementation that provided these operations? Do we have use-cases where we read/write base64-encoded stuff from/to the network (meaning `Cstruct.t -> Cstruct.t`)?
    ```ocaml
        val b64_to_bin_s : string -> Cstruct.t (* decode PEM certs from e.g. Mirage_kv *)
        val bin_to_b64_s : Cstruct.t -> string (* encode PEM certs to e.g. *)
    ```
    Would it makes sense to try to synthesize additional benchmarks for those two signatures for each of these four implementations so we have numbers that are more relevant to our use-cases?

**Comment by hannesm** [comment]
@cfcs I am not entirely sure what you're up to, but (a) mirage-crypto _does_ _not_ _use_ base64, but some clients (e.g. x509) use it. (b) I suspect the clients could as well do `(Base64.encode (Cstruct.to_string yyy))` themselves (i.e. no need to provide this in base64).

I am still unsure about cstruct/string/bytes/cstruct_cap (and thus would appreciate a more mirageos-global decision on which char array presentation to use at which time, instead of the current topsy-turvy model).

**Comment by cfcs** [comment]
Sorry, didn't think that through.
`git grep` shows the only usage is in the `tests/`, so I'd be in favor of relegating the task of encoding/decoding base64 to whoever needs that, which they could then do with `ocaml-base64` or whatever. It's IMHO not a crypto primitive, and on top of that I guess it's not really performance-sensitive either for our users either, so I don't think we need to maintain our own version here.

**Comment by cfcs** [comment]
+1 on byte vector representation circus. At the retreat perhaps? Will you be joining @dinosaure?

**Comment by dinosaure** [comment]
Yes, I will join the retreat :+1:

**Comment by cfcs** [comment]
@dinosaure with #29, I think we can close this? :) (and I guess move the discussion to `ocaml-x509`)
