### ISSUE TITLE
Document the responsibilities of the consumer

### ISSUE THREAD

**Issue by cfcs** [mirage/mirage-crypto#26]
We should document the responsibilities of the consumer when it comes to providing inputs for various functions, e.g. what input validation the consumer is up to the user versus the user can expect the library to complain about.

This ties in with developing / documenting the threat models we consider for each API endpoint.

Consider the following example where an attacker can provide a (very small) `public key`, a `message`, and an alleged `signature` to a program that performs PKCS1 signature validation.

We will not allow our own users to generate such a signature (`SHA256`) with a key less than 489 bits, but we are happy to attempt validation, in the worst case with an endless loop as the result.

It follows that the user should not pass in "too small keys," or alternatively that we should perform validation thereof. In either case we should probably detail somewhere what "too small" entails.

```ocaml
#require "mirage-crypto-pk";;
#require "mirage-crypto-rng.unix";;
Mirage_crypto_rng_unix.initialize ();;
let rec attacker_provides keylen =
  (* bad person provides: *)
  let open Mirage_crypto_pk.Rsa in
  let small_priv = generate ~e:(Z.of_int 3) keylen in
  let small_pub = pub_of_priv small_priv in
  let hash = `SHA256 in
  let msg = Cstruct.(of_string @@ String.make (keylen/8) 'a') in
  let signature =  Cstruct.(of_string @@ String.make (keylen/8) 'a') in
  small_pub, hash, msg, signature
and verifier_computes bad_key_len =
  let pub, hash_algo, msg, signature = attacker_provides bad_key_len in
  assert (List.exists ((=) hash_algo)  [`SHA256] ); (* consumer discards MD5 etc *)
  let digest = Mirage_crypto.Hash.digest hash_algo msg in
   Mirage_crypto_pk.Rsa.PKCS1.verify ~key:pub ~hashp:(fun x -> x = hash_algo)
   (`Digest digest) ~signature
;;

verifier_computes 15;;
(* As expected: - : bool = false *)

verifier_computes 8;;
(* Endless loop. A consumer has no way to recover from this. *)

verifier_computes 16;;
(* undocumented exception from Mirage_Crypto_pk.Rsa.PKCS1.verify:
Exception: (Invalid_argument "invalid bounds in Cstruct.get_uint8 [0,2](2) off=2 len=1")
*)
```

**Comment by hannesm** [comment]
thanks for your issue.

I'm curious what is left to do here once #28 is merged, which (a) made public key structures private, and validates input thereof, and for the example above has a minimum octet length of RSA modulus to be 12 bytes (or 89 bits) to avoid PKCS1 troubles; and (b) removed some exceptions on its way.

**Comment by cfcs** [comment]
I think #28 addresses both the concrete example and the `private` barrier for public keys addresses the general concern. I'm very happy with this, and I think we can close this. :)
