### ISSUE TITLE
improve CI setup (ocamlformat, doc target)

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage-crypto#35]
- use + require ocamlformat (evaluate whether it it stable yet -- not keen to upgrade every other week to a slightly different format)?
- build doc target (to spot warnings and errors)

--> is this possible with ocaml-ci out of the box?

**Comment by avsm** [comment]
ocaml-ci can do doc target once https://github.com/ocurrent/ocaml-ci/pull/105 is merged, cc @talex5 @craigfe

**Comment by hannesm** [comment]
closing, ocaml-ci does a fine job. ocamlformat is still under heavy development, waiting for a stable release.
