### ISSUE TITLE
Use dune's variants and trick on the META file

### ISSUE THREAD

**Issue by dinosaure** [mirage/mirage-crypto#46]
This issue wants to solve an initial and systematic issue found into `checkseum`/`digestif` and try to prepare an easily move to `mirage` with `dune`. To contextualize a bit the goal of this issue, you probably should look into mirage/mirage#1024.

Come back to the _dunification_ of MirageOS, the main and fully described difference of the compilation of an _unikernel_ with `ocamlbuild` and with `dune` is the option: `-output-complete-obj`. The main difference is about static C libraries. Let back a bit about the diff.

#### Link an _unikernel_ with `ocamlbuild` + `ocamlfind`

According the current status of MirageOS, a library with C stubs such as `checkseum` must fill a `META` file with some _metadata_ to let the `mirage` tool to choose the right static C library according the target. `mirage` asks with `ocamlfind` these _metadata_ and put at the link-time with `-output-obj` static libraries collected.

The compiler, at the link time and **with** `-output-obj` does not care about static libraries described into `*.cmxa`. This is why the `mirage` tool/`ocamlbuild`/`ocaml` **can** chooses the right static C libraries such as `-lgmp-freestanding` (for Solo5) according the target (even if `zarith.cmxa` describes `-lgmp`).

#### Link an _unikernel_ with `dune`

However, `dune` strictly uses a new option of the compiler, `-output-complete-obj` and it seems that `-output-obj` will be deprecated. This new option change the behavior of the compiler where it wants to link the final `main.o` (the _unikernel_) with libraries described into `*.cmxa` used to produce the _unikernel_.

A link with `zarith.cmxa` with `-output-complete-obj` will try (at the compiler layer) to link with `libgmp.a` in any cases.

#### For a library such as `checkseum` (and `mirage-crypto`)

Of course, for any libraries which wants to provide C stubs, a compilation of the _unikernel_ with `-output-complete-obj` constraints us to:
1) still continue to provide a `META` file with such _metadata_ to be compatible with MirageOS 3.*
2) provides well-formed `*.cmxa` with right C libraries such as:
    + `checkseum_freestanding.cmxa` should link with `-lcheckseum_freestanding`
    + `checkseum_xen.cmxa` should link with `-lcheckseum_xen`

The second point is a requirement of the compiler due to the use of `-output-complete-obj`. The first point is the well-know requirement for MirageOS 3.*.

A question still exists however. Who and how we can choose between `checkseum_freestanding` and `checkseum_xen` according the target expected by the user? This is where `dune` can come and choose one of these libraries according an explicit expected _variant_.

I will not try to explain, again, _variant_ but it unlock the ability for a user to choose an implementation (compiled object for Solo5, compiled object for Xen, etc.) according a common interface according a new field. `dune` is able to choose a _default_ implementation if the field is missed (such as the `unix` target).

Under the use of variant, we have the ability to produce well-formed `*.cmxa` and each of them will have the same interface (technically, the same hash of the common interface).

#### A story about compatibility

However, if we choose to use variants and provide well-formed `*.cmxa` and help a bit the compiler to link with right static C libraries, we are not able to play with the `META` file. Of course, after some iterations, we did it (mostly on `checkseum`): you can look it [here](https://github.com/mirage/checkseum/blob/master/checkseum.opam#L19-L29).

#### The final task

At the end, if we want to use `dune` to compile an _unikernel_, we must provides well-formed `*.cmxa` because of `-output-complete-obj`. The question about the way to choose which `*.cmxa` we will choose according the target is **the main problem**:
- For MirageOS.3.*, this is done by `ocamlfind`
- For a MirageOS with `dune`, it should be done by `dune` at least
- An other solution exists with `duniverse`

To be smooth about such a transition, the first and the second point can live together. Of course, the solution is not perfect when:
- we must hack the `META` file by ourselves
- we must use `dune`'s variants
- the compilation to an executable (which uses the library with C stubs) with something else than `dune` will not properly work (due to the _linking-trick_).

However, I think it could be a good solution to pave the way to the _dunification_ of MirageOS and give to use an intermediate step which is still compatible with both worlds.

##### Technically. what we should do

The task is to use `dune`'s _variants_, so an update of:
- `freestanding/dune`
- `xen/dune`
- `src/native/dune`
is needed to specify which variants they are. Then, we must trick on the OPAM file to rightly put _metadata_ needed by `ocamlfind` such as `checkseum` does.

So, for any questions, I'm free to go deeply into details and explain goals.

**Comment by hannesm** [comment]
I think I understand that this is related to the build system (and am happy to switch to dune with MirageOS) -- one remainder would be to check the binary and performance of (likely in a MirageOS 3 environment) mirage-crypto as-is compared to it using variants. I'd expect the binary to be "mostly equal", the performance should not be affected (but we should measure that e.g. the AES performance does not drop -- both on the common unix target, but as well on a unikernel). If the performance drops, we should investigate this. I can conduct this experiment at some point this week and report back.

**Comment by hannesm** [comment]
and a PR that uses variants for mirage-crypto's C code would be very welcome, btw. I'm sure you're much faster at doing this than myself.

**Comment by hannesm** [comment]
since MirageOS4 uses a slightly different story, this is no longer needed (but `:standard` needs to be part of the c_flags, as it is in mirage-crypto)
