### ISSUE TITLE
Compile errors on aarch32

### ISSUE THREAD

**Issue by TImada** [mirage/mirage-crypto#60]
I found `dune build` on aarch32 results in multiple errors due to `__uint128_t` not supported by 32-bit gcc.

```
imada@ubuntu:~/mirage/mirage-crypto$ dune build
      ocamlc freestanding/ghash_generic.o (exit 2)
...
src/native/ghash_generic.c:23:14: error: unknown type name ‘__uint128_t’
src/native/ghash_generic.c:21:36: error: ‘__uint128_t’ undeclared here (not in a function); did you mean ‘__int128’?
src/native/ghash_generic.c:23:30: note: in expansion of macro ‘__set_uint128_t’
src/native/ghash_generic.c:23:47: error: expected ‘)’ before numeric constant
src/native/ghash_generic.c:21:49: note: in definition of macro ‘__set_uint128_t’
...
...
```

The current `mirage-crypto-entropy.opam` indicates 32-bit arm and x86 as available architecture, `x86_32` will have the same errors too.
```
available: [
  arch = "arm" | arch = "x86_32" | arch = "x86_64" | arch = "arm64"
]
```

https://github.com/mirage/mirage-crypto/commit/7d67013f22230290021ab10937d8e72698fab3e9 seems the first commit which employed `__uint128_t`.

**Comment by hannesm** [comment]
thanks for your report, I'll fix this in the next release.

**Comment by TImada** [comment]
Many thanks!

I found Ruby guys were discussing a similar topic. https://bugs.ruby-lang.org/issues/16234
Drone CI seems to work for a variety of 32/64-bit architecture.
