### ISSUE TITLE
No known cycle-counting instruction on ppc64

### ISSUE THREAD

**Issue by talex5** [mirage/mirage-crypto#75]
`mirage-crypto` fails to install on ppc64:

```
#=== ERROR while compiling mirage-crypto.0.8.1 ================================#
# context              2.0.7 | linux/ppc64 | ocaml-base-compiler.4.10.0 | file:///home/opam/opam-repository
# path                 ~/.opam/4.10/.opam-switch/build/mirage-crypto.0.8.1
# command              ~/.opam/4.10/bin/dune build -p mirage-crypto -j 79
# exit-code            1
# env-file             ~/.opam/log/mirage-crypto-8-9e20af.env
# output-file          ~/.opam/log/mirage-crypto-8-9e20af.out
### output ###
#       ocamlc src/entropy_cpu_stubs.o (exit 2)
# (cd _build/default/src && /home/opam/.opam/4.10/bin/ocamlc.opt -g -I /home/opam/.opam/4.10/lib/bigarray-compat -I /home/opam/.opam/4.10/lib/cstruct -I /home/opam/.opam/4.10/lib/eqaf -I /home/opam/.opam/4.10/lib/eqaf/bigstring -I /home/opam/.opam/4.10/lib/eqaf/cstruct -ccopt -O2 -ccopt -fno-strict-aliasing -ccopt -fwrapv -ccopt -fPIC -ccopt --std=c99 -ccopt -Wall -ccopt -Wextra -ccopt -Wpedantic -ccopt -O3 -ccopt -g -o entropy_cpu_stubs.o native/entropy_cpu_stubs.c)
# native/entropy_cpu_stubs.c: In function 'caml_cycle_counter':
# native/entropy_cpu_stubs.c:86:2: error: #error ("No known cycle-counting instruction.")
#  #error ("No known cycle-counting instruction.")
#   ^~~~~
# native/entropy_cpu_stubs.c:88:1: warning: control reaches end of non-void function [-Wreturn-type]
```

Any suggestions on how to get this working?

**Comment by avsm** [comment]
This fragment from https://stackoverflow.com/questions/5883124/whats-the-equivalent-of-rdtsc-opcode-for-ppc may help...

```
unsigned long long rdtsc(){
        unsigned long long rval;
        __asm__ __volatile__("mfspr %%r3, 268": "=r" (rval));
        return rval;
}
```

**Comment by dinosaure** [comment]
[`gperftool`](https://chromium.googlesource.com/external/gperftools/+/master/src/base/cycleclock.h#81) (an old version) has a _portable_ implementation of RDTSC.

**Comment by hannesm** [comment]
ftr, I don't have any ppc64 to test the code on. I'd not be in favor to add https://github.com/talex5/mirage-crypto/commit/04169eeb7947ee19d80ec032d747a7e8639f1693 to the main branch, but if the [code from stackoverflow]https://github.com/mirage/mirage-crypto/issues/75#issuecomment-657545852() works (maybe someone has time to check with the ppc64 instruction set manual), I'd be happy to merge that. Is there a ppc64 CI now?

**Comment by talex5** [comment]
> Is there a ppc64 CI now?

I'm trying to set one up. But the build agent it needs to run uses mirage-crypto to communicate with the build scheduler, so it won't install yet...

(I do have a work-around for now though)
