### ISSUE TITLE
decrypted message has \u0000 left padding

### ISSUE THREAD

**Issue by SahanaKrishnaKarki** [mirage/mirage-crypto#80]
The RSA encryption algorithm adds left padding \u0000 in the decrypted message.Is there any way to remove the padding?

"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000[\"abc\",\"xyz\",\"pqr\"]"

**Comment by hannesm** [comment]
Hello @SahanaKrishnaKarki, I do not entirely understand what you try to do. Conventionally, RSA encryption uses some form of padding (e.g. https://mirage.github.io/mirage-crypto/doc/mirage-crypto-pk/Mirage_crypto_pk/Rsa/OAEP/index.html or the older https://mirage.github.io/mirage-crypto/doc/mirage-crypto-pk/Mirage_crypto_pk/Rsa/PKCS1/index.html#val-decrypt).

It looks like you're using the Rsa.decrypt directly (https://mirage.github.io/mirage-crypto/doc/mirage-crypto-pk/Mirage_crypto_pk/Rsa/index.html#val-decrypt) which is documented with "left-padded with 0x00 up to key size" (that's what OAEP/PKCS1 rely on internally).

I suggest to use OAEP/PKCS1 encryption modes instead. If you insist on raw RSA decryption, you'll have to remove the padding yourself.
